const BASE_IPFS_URI = 'ipfs://<ipfsdibase>';

// Collection metadata
const SQUAD_METADATA = BASE_IPFS_URI + '/metadata/timeSquad/collection_metadata_squad.json';
const SQUAD_ITEM_METADATA = BASE_IPFS_URI + '/metadata/items/collection_metadata_item.json';

// Catalog metadata
const SQUAD_CATALOG_RYKER_METADATA = BASE_IPFS_URI + '/catalog/catalogRyker.json';
const SQUAD_CATALOG_LUNA_METADATA = BASE_IPFS_URI + '/catalog/catalogluna.json';
const SQUAD_CATALOG_ARIA_METADATA = BASE_IPFS_URI + '/catalog/catalogAria.json';
const SQUAD_CATALOG_THADDEUS_METADATA = BASE_IPFS_URI + '/catalog/catalogThaddeus.json';

const SQUAD_ITEM_LEFT_SLOT_METADATA = BASE_IPFS_URI + 'catalog/slots/left_hand.json';  //{ "name": "Left Hand" }
const SQUAD_ITEM_RIGHT_SLOT_METADATA = BASE_IPFS_URI + 'catalog/slots/right_hand.json';
const SQUAD_ITEM_CAP_SLOT_METADATA = BASE_IPFS_URI + 'catalog/slots/cap_.json';
const SQUAD_ITEM_ARMOR_SLOT_METADATA = BASE_IPFS_URI + 'catalog/slots/armor.json';

// FIXED PARTS

// SLOT PARTS, sono uguali per ogni catalog
const SQUAD_LEFT_HAND_SLOT_PART_ID = 1001;
const SQUAD_RIGHT_HAND_SLOT_PART_ID = 1002;
const SQUAD_CAP_SLOT_PART_ID = 1003;
const SQUAD_ARMOR_SLOT_PART_ID = 1004;

// PART TYPES (Defined by standard)
const PART_TYPE_SLOT = 1;
const PART_TYPE_FIXED = 2;

// Z INDEXES per le immagini svg (sia fixed che slot part)
const Z_INDEX_BODY = 2;
const Z_INDEX_LEFT_HAND_ITEMS = 4;
const Z_INDEX_RIGHT_HAND_ITEMS = 4;
const Z_INDEX_CAP_ITEMS = 4;
const Z_INDEX_ARMOR_ITEMS = 4;


// Equippable groups
const EQUIPPABLE_GROUP_FOR_CHUNKIES_DEFAULT = 1; // Only in case we want all chunkies to be later equippable into something
const EQUIPPABLE_GROUP_FOR_ITEMS_LEFT_HAND = SQUAD_LEFT_HAND_SLOT_PART_ID;
const EQUIPPABLE_GROUP_FOR_ITEMS_RIGHT_HAND = SQUAD_RIGHT_HAND_SLOT_PART_ID;
const EQUIPPABLE_GROUP_FOR_ITEMS_CAP = SQUAD_CAP_SLOT_PART_ID;
const EQUIPPABLE_GROUP_FOR_ITEMS_ARMOR = SQUAD_ARMOR_SLOT_PART_ID;

// Image data
const SQUAD_ITEM_BASE_METADATA_URI = BASE_IPFS_URI + '/items/';

  export {
    BASE_IPFS_URI,
    SQUAD_METADATA,
    SQUAD_ITEM_METADATA,
    SQUAD_CATALOG_RYKER_METADATA,
    SQUAD_CATALOG_LUNA_METADATA,
    SQUAD_CATALOG_ARIA_METADATA,
    SQUAD_CATALOG_THADDEUS_METADATA,
    SQUAD_ITEM_LEFT_SLOT_METADATA,
    SQUAD_ITEM_RIGHT_SLOT_METADATA,
    SQUAD_ITEM_CAP_SLOT_METADATA,
    SQUAD_ITEM_ARMOR_SLOT_METADATA,
    SQUAD_LEFT_HAND_SLOT_PART_ID,
    SQUAD_RIGHT_HAND_SLOT_PART_ID,
    SQUAD_CAP_SLOT_PART_ID,
    SQUAD_ARMOR_SLOT_PART_ID,
    PART_TYPE_SLOT,
    PART_TYPE_FIXED,
    Z_INDEX_BODY,
    Z_INDEX_LEFT_HAND_ITEMS,
    Z_INDEX_RIGHT_HAND_ITEMS,
    Z_INDEX_CAP_ITEMS,
    Z_INDEX_ARMOR_ITEMS,
    EQUIPPABLE_GROUP_FOR_CHUNKIES_DEFAULT,
    EQUIPPABLE_GROUP_FOR_ITEMS_LEFT_HAND,
    EQUIPPABLE_GROUP_FOR_ITEMS_RIGHT_HAND,
    EQUIPPABLE_GROUP_FOR_ITEMS_CAP,
    EQUIPPABLE_GROUP_FOR_ITEMS_ARMOR,
    SQUAD_ITEM_BASE_METADATA_URI
};

